name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install -r ./requirements.txt
        pip install -r ./test-requirements.txt
    - name: Build package
      run: python -m build
    - name: Test package
      run: pytest -s -v --cov=Avalara.SDK --username=${{ secrets.API_USERNAME }} --password=${{ secrets.API_PASSWORD }}
